import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import DefaultLayout from "@/components/layout/defaultLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <DefaultLayout>{children}</DefaultLayout>
        </StoreProvider>
      </body>
    </html>
  );
}
